### ISSUE TITLE
build error: reobfJar FAILED (duplicate entry: seppuku_at.cfg)

### ISSUE THREAD

**Issue by ChillerDragon** [seppukudevelopment/seppuku#47]
```
$ java -version
openjdk version "1.8.0_265"
OpenJDK Runtime Environment (build 1.8.0_265-8u265-b01-0+deb9u1-b01)
OpenJDK 64-Bit Server VM (build 25.265-b01, mixed mode)
```

```
$ ./gradlew build

> Configure project :
This mapping 'stable_39' was designed for MC 1.12! Use at your own peril.
Found AccessTransformer: seppuku_at.cfg

> Task :reobfJar FAILED

> Task :extractAnnotationsJar
Error while building FML annotations cache: duplicate entry: seppuku_at.cfg
java.util.zip.ZipException: duplicate entry: seppuku_at.cfg
        at java.util.zip.ZipOutputStream.putNextEntry(ZipOutputStream.java:232)
        at net.minecraftforge.gradle.user.TaskExtractAnnotations.processJar(TaskExtractAnnotations.java:96)
        at net.minecraftforge.gradle.user.TaskExtractAnnotations.doTask(TaskExtractAnnotations.java:69)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:794)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:761)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
        at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$ExecuteTaskAction.execute(DefaultTaskExecutionGraph.java:262)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$ExecuteTaskAction.execute(DefaultTaskExecutionGraph.java:246)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:136)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.execute(DefaultTaskPlanExecutor.java:201)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.executeWithTask(DefaultTaskPlanExecutor.java:192)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.lang.Thread.run(Thread.java:748)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':reobfJar'.
> java.util.zip.ZipException: duplicate entry: seppuku_at.cfg

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.8.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 2s
12 actionable tasks: 6 executed, 6 up-to-date

```

**Comment by wine** [comment]
Try clearing the cache.

**Comment by ChillerDragon** [comment]
Its a fresh build but how does one clear the cache?

**Comment by jvyden** [comment]
On Sun, 11 Oct 2020 13:56:20 -0700
Chiller Dragon <notifications@github.com> wrote:

> Its a fresh build but how does one clear the cache?
> 

usually it's `./gradlew clean`

**Comment by jvyden** [comment]
actually it could potentially be because you've set the buildmode in build.gradle incorrectly; are you just looking to make a .jar or are you running minecraft in an IDE?

**Comment by Old-Chum** [comment]
Looks like what was discussed here #16

**Comment by jvyden** [comment]
On Sun, 11 Oct 2020 14:51:42 -0700
Old Chum <notifications@github.com> wrote:

> Looks like what was discussed here #16 
> 

i thought i vaguely remembered this issue

should we close this and move discussion there, then?

**Comment by ChillerDragon** [comment]
Oh yea I did not edit the build.gradle because it is some release vs debug and I like running in debug. Why is the project setup in a way that one has to edit the build script to get a successful build?

**Comment by uoil** [comment]
Glad you got it sorted out, there really shouldn't be a secondary step needed to get the project to build after cloning, but it's just how it is set up right now to change between building release jars and debugging. I like the idea of a CLI arg though

**Comment by ChillerDragon** [comment]
> > Oh yea I did not edit the build.gradle because it is some release vs debug and I like running in debug. Why is the project setup in a way that one has to edit the build script to get a successful build?
> > EDIT: Oh I guess to make IDE development easier. Hm what about a cli arg instead of editing a file that is tracked in git? Like `./gradlew release`
> > btw editing the build.gradle file did the job and I built fine :)
> 
> what did you edit to get it to work?

Tbh I can not remember. I probably followed the instructions from #16 which would be replacing "IDE" in the gradle.build with "RELEASE" here I guess

https://github.com/seppukudevelopment/seppuku/blob/19bbb8a5e73721a4f23a02286bc8c51873a94258/build.gradle#L24

**Comment by ChillerDragon** [comment]
Yea looks correct according to the readme

https://github.com/seppukudevelopment/seppuku/tree/19bbb8a5e73721a4f23a02286bc8c51873a94258#linux-unix-and-mac

**Comment by uoil** [comment]
Each time after editing the line in build.gradle run `gradle clean`  and building should work fine afterwards

**Comment by uniformization** [comment]
> > > Oh yea I did not edit the build.gradle because it is some release vs debug and I like running in debug. Why is the project setup in a way that one has to edit the build script to get a successful build?
> > > EDIT: Oh I guess to make IDE development easier. Hm what about a cli arg instead of editing a file that is tracked in git? Like `./gradlew release`
> > > btw editing the build.gradle file did the job and I built fine :)
> > 
> > 
> > what did you edit to get it to work?
> 
> Tbh I can not remember. I probably followed the instructions from #16 which would be replacing "IDE" in the gradle.build with "RELEASE" here I guess
> 
> https://github.com/seppukudevelopment/seppuku/blob/19bbb8a5e73721a4f23a02286bc8c51873a94258/build.gradle#L24

I had the issue with my personal project and I just fixed it by removing the sourceSets block.
