### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by master7720** [seppukudevelopment/seppuku#90]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  SeppukuLoadingPlugin (seppuku-3.1.8.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 10/29/21 8:05 PM
Description: Initializing game

java.lang.IllegalArgumentException: Multiple entries with same key: seppukumod=FMLMod:seppukumod{3.1.7} and seppukumod=FMLMod:seppukumod{3.1.7}. To index multiple values under a key, use Multimaps.index.
	at com.google.common.collect.Maps.uniqueIndex(Maps.java:1385)
	at com.google.common.collect.Maps.uniqueIndex(Maps.java:1341)
	at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:429)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:568)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.google.common.collect.Maps.uniqueIndex(Maps.java:1385)
	at com.google.common.collect.Maps.uniqueIndex(Maps.java:1341)
	at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:429)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:568)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 791022416 bytes (754 MB) / 1073741824 bytes (1024 MB) up to 3221225472 bytes (3072 MB)
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -Xverify:none
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 6 mods loaded, 0 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID         | Version      | Source                        | Signature                                |
	|:----- |:---------- |:------------ |:----------------------------- |:---------------------------------------- |
	|       | minecraft  | 1.12.2       | minecraft.jar                 | None                                     |
	|       | mcp        | 9.42         | minecraft.jar                 | None                                     |
	|       | FML        | 8.0.99.99    | forge-1.12.2-14.23.5.2855.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	|       | forge      | 14.23.5.2855 | forge-1.12.2-14.23.5.2855.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	|       | seppukumod | 3.1.7        | seppuku-3.1.8.jar             | None                                     |
	|       | seppukumod | 3.1.7        | seppuku-3.1.8.jar             | None                                     |

	Loaded coremods (and transformers): 
SeppukuLoadingPlugin (seppuku-3.1.8.jar)
  me.rigamortis.seppuku.impl.fml.core.SeppukuClassTransformer
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 20.19.15.5058' Renderer: 'Intel(R) HD Graphics 5500'
	Launched Version: 1.12.2-forge-14.23.5.2855
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 5500 GL version 4.4.0 - Build 20.19.15.5058, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Zenith 1.12.2 pack V5
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz

**Comment by uoil** [comment]
Use the seppuku-3.1.8-full.jar
